### PR TITLE
Download progress

### PR DESCRIPTION
**Pull request by mpetrasinovic**

### CODE REVIEW

**Comment by padcom** [comment]
Thanks for the PR!

I like the idea of adding progress information to the `downloadFile` and `readFile`. Might I suggest you do those as optional parameters with destructuring:


```
type ProgressCallback = (offset: number, totalSize: number) => void

private async readFile(size: number, {
  progress?: ProgressCallback,
})
```

(same for `downloadFile`)

Also, the other arguments for callback are kind of application-specific so I'd leave them out as well as the calculation thereof. Let's keep things simple.

That way, extending the interface of those two functions further (for whatever reason) will not enforce an akward check which parameter is which.

**Comment by mpetrasinovic** [comment]
Unfortunately, I am not using typescript, so I am not sure how to do it as you suggested. I agree with your conclusion about other arguments.

**Comment by padcom** [comment]
Ok, check if this branch works for you:

https://github.com/padcom/node-mavlink-ftp/blob/feature/download-file-progress/index.ts#L364

**Comment by mpetrasinovic** [comment]
Looking good. Thank you!

**Comment by padcom** [comment]
> Looking good. Thank you!

Have you tried if it works? If it does I'll merge it.

**Comment by mpetrasinovic** [comment]
I tried it now, and I can confirm that it works as expected.  Maybe this package should no longer be in alpha.

**Comment by padcom** [comment]
Implemented via feature/download-file-progress

**Comment by padcom** [comment]
Released as 0.0.1, no longer "alpha". Thanks @mpetrasinovic for testing!

**Pull request closed without merging**
